# Generated by Django 3.2.6 on 2021-09-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
