# Generated by Django 3.2.7 on 2021-09-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_alter_hike_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='description',
            field=models.TextField(max_length=100000),
        ),
    ]
